microblog/urls.py
from django.conf.urls import patterns, include, url

#improt our settings file to serve static assets
from django.conf import settings
from microblogs.views import index
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'microblog.views.home', name='home'),
    # url(r'^microblog/', include('microblog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # hands off the request to the microblogs app
    url(r'^blog/', include('microblogs.urls', namespace="microblogs")),

    # homepage url is outside of the "microblogs" namespace hence no colon
    url(r'^$', index, name='index'),

    # url to match djangos requests for assets (js, css, img) and return them
    # change settings.Dev.... to STATIC_ROOT for production deployment (remember to run collectstatic too)
    # collectstatic pulls static files i.e. js and css and html( files that change often)
    # to the django files (files or infrastructure that will never change or rarely does)
    # so django can put them together to make the awesomeness that is a web page
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

microblogs/urls.py
from django.conf.urls import patterns, url
from microblogs import views
from microblogs.views import blog_list, blog_detail

urlpatterns = patterns('',
#heres a comment

    url(r'^$', blog_list, name ='blog_list'),
    url(r'^(?P<pk>\d+)/$', blog_detail, name= 'blog_detail'),
)

microblogs/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.


class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, default='')
    content = models.TextField()
    published = models.BooleanField(default=True)
    author = models.ForeignKey(User, related_name="post")

    class Meta:
        ordering = ["-created_at", "title"]

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        # call super so it does the work defined in model.model.save
        super(Post, self).save(*args, **kwargs)

microblogs/views.py
# Create your views here.
from django.shortcuts import render
from models import Post
from django.http import HttpResponse
from restless.models import serialize
from django.core.serializers.json import DjangoJSONEncoder
import json


def index(request):
    return render(request, 'index.html')


def blog_list(request, *args, **kwargs):
    post_list = (Post.objects.filter(published=True))

    # were going to serialize the data into json and return it via the url
    # first i found this package called Django restless that removes the model and the pk valies
    # but it formatted it as a unicode string
    # then i imported json and dumped that unicode string into it, along with DjangoEncoder
    # as a cls and it worked perfectly
    # the result: a perfectly json formatted string with the info you dont want shown hiddden
    # and the fields brought to the root level
    data = serialize(post_list)
    jsondata = json.dumps(data, cls=DjangoJSONEncoder)

    return HttpResponse(jsondata, mimetype='application/json')


def blog_detail(request, pk, *args, **kwargs):
    # were going to serialize the data into json and return it via the url
    # with this object using .get is not iterable because it only returns one item
    # post = Post.objects.get(pk=pk, published=True) soooo..you have to  use
    post = Post.objects.filter(pk=pk, published=True)
    data = serialize(post)
    jsondata = json.dumps(data, cls=DjangoJSONEncoder)

    return HttpResponse(jsondata, mimetype='application/json')

templates/base.html
{% load static from staticfiles %}
{% load url from future %}  {# Deprecated in django 1.6 #}

<!doctype html>
<html lang="en">

{% block head %}
<head>
    <meta charset="UTF-8">

    {% block css %}
    {# in the href you put static as shown here to tell django that this is a static file coming #}
    {# from the static folder you provided and the rest is just a regular url #}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    {% endblock css %}

    <title>{% block page_title %}{% endblock %}Microblog</title>

</head>
{% endblock head %}


    <body>
        <div class="container">
            {% block page_content %}{%  endblock %}
        </div>
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load url from future %}
<!DOCTYPE html>
{% block head %}

<head>
    <title>Jon Hairston's Page</title>

</head>
    {{ block.super }}
{% endblock %}
<body>
    {% block page_content %}
        <h1>Hello Woild!!!!!!</h1>
        <h2>This is my page. This is the first step in ALL YOUR BASE BELONG TO US!!!!1!!!!1!</h2>
        Words.That is all.
        <h3><a class="btn" href="{% url 'microblogs:blog_list' %}">List o Blogs</a></h3>
    {% endblock %}
</body>
</html>

templates/post_detail.html
{% extends "base.html" %}
{% load url from future %}
{% block page_title %}{{ post.title }} | {% endblock %}

{% block page_content %}
<h2>{{ post.title | linebreaks }}</h2>
   <h3><a class="btn" href="{% url 'microblogs:blog_list' %}">&larr; Blog list</a></h3>
  <p>{{ post.content |linebreaks }}</p>
<p>{{  post.updated_at }}</p>
    <h3><a class="btn" href="{% url 'microblogs:blog_list' %}">&larr; Blog list</a></h3>
{% endblock %}

templates/post_list.html
{% extends "base.html" %}
{% load url from future %}

{% block page_title %}Blog Posts | {% endblock %}

{% block page_content %}
    <h1>Welcome to my blog</h1>
    <h2>Blog Posts</h2>

<ul>
    {% for post in post_list %}
{# If you namespaced the apps url then you need to do app:app's url to not get that #}
{# no reverse match error, which happens because django doesn't know which view goes with what app #}
    <li><h2><a href="{% url 'microblogs:blog_detail' post.pk %}">{{ post.title }}</a></h2></li>
    {% empty %}
    <h2>Sorry, no posts yet. Check back soon!</h2>
    {% endfor %}
</ul>
    <h3><a class="btn" href="{% url 'index' %}">&larr; Back to Main Page</a></h3>
{% endblock %}